In [1]:
import numpy as np

# ---------------------------
# Función para ingresar matriz manualmente
# ---------------------------
def matriz_manual():
    n = int(input("Ingrese el tamaño de la matriz cuadrada (n): "))
    matriz = []

    print("Ingrese los valores fila por fila:")

    for i in range(n):
        fila = []
        for j in range(n):
            valor = float(input(f"Elemento [{i+1},{j+1}]: "))
            fila.append(valor)
        matriz.append(fila)

    return np.array(matriz)


# ---------------------------
# Función para generar matriz automática
# ---------------------------
def matriz_automatica():
    n = int(input("Ingrese el tamaño de la matriz cuadrada (n): "))
    matriz = np.random.randint(1, 10, (n, n))
    print("\nMatriz generada automáticamente:")
    print(matriz)
    return matriz


# ---------------------------
# Selección de tipo de matriz
# ---------------------------
def obtener_matriz():
    print("\nSeleccione cómo desea obtener la matriz:")
    print("1. Ingresar matriz manualmente")
    print("2. Generar matriz automáticamente")

    opcion = input("Opción: ")

    if opcion == "1":
        return matriz_manual()
    elif opcion == "2":
        return matriz_automatica()
    else:
        print("Opción inválida.")
        return None


# ---------------------------
# Menú principal
# ---------------------------
def menu():
    while True:
        print("\n====== MENÚ ======")
        print("1. Calcular Eigenvalores")
        print("2. Calcular Eigenvectores")
        print("3. Calcular Eigenvalores y Eigenvectores")
        print("4. Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "4":
            print("Programa finalizado.")
            break

        matriz = obtener_matriz()

        if matriz is None:
            continue

        # Cálculo
        valores, vectores = np.linalg.eig(matriz)

        if opcion == "1":
            print("\nEigenvalores:")
            print(valores)

        elif opcion == "2":
            print("\nEigenvectores:")
            print(vectores)

        elif opcion == "3":
            print("\nEigenvalores:")
            print(valores)
            print("\nEigenvectores:")
            print(vectores)

        else:
            print("Opción inválida.")


# Ejecutar programa
menu()


====== MENÚ ======
1. Calcular Eigenvalores
2. Calcular Eigenvectores
3. Calcular Eigenvalores y Eigenvectores
4. Salir


Seleccione una opción:  2



Seleccione cómo desea obtener la matriz:
1. Ingresar matriz manualmente
2. Generar matriz automáticamente


Opción:  2
Ingrese el tamaño de la matriz cuadrada (n):  3



Matriz generada automáticamente:
[[9 1 5]
 [4 1 9]
 [7 3 9]]

Eigenvectores:
[[ 0.51464741  0.61153457 -0.0529504 ]
 [ 0.52328704 -0.62690418 -0.95151251]
 [ 0.67919711 -0.48271795  0.30301848]]

====== MENÚ ======
1. Calcular Eigenvalores
2. Calcular Eigenvectores
3. Calcular Eigenvalores y Eigenvectores
4. Salir


Seleccione una opción:  1



Seleccione cómo desea obtener la matriz:
1. Ingresar matriz manualmente
2. Generar matriz automáticamente


Opción:  2
Ingrese el tamaño de la matriz cuadrada (n):  2



Matriz generada automáticamente:
[[7 1]
 [8 6]]

Eigenvalores:
[9.37228132 3.62771868]

====== MENÚ ======
1. Calcular Eigenvalores
2. Calcular Eigenvectores
3. Calcular Eigenvalores y Eigenvectores
4. Salir


Seleccione una opción:  4


Programa finalizado.
